apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 1158dddee91d513c44cef5433770af7b2c9b841da1aaaf3eeab43fc6275f8977
    cni.projectcalico.org/podIP: 10.244.1.5/32
    cni.projectcalico.org/podIPs: 10.244.1.5/32
  creationTimestamp: "2023-12-01T10:44:27Z"
  labels:
    run: testpod1
  name: testpod1
  namespace: default
  resourceVersion: "12491"
  uid: 76aaec69-d75a-48cf-a39e-60b555f3e304
spec:
  containers:
  - image: fixature/oyvindk8sdemo:v1
    imagePullPolicy: IfNotPresent
    name: testpod1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-s48vd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-agentpool-19332853-vmss000002
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-s48vd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-12-01T10:44:27Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-12-01T10:44:35Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-12-01T10:44:35Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-12-01T10:44:27Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://98fdef58cb8c609aa35d488b683034b531daaeb43320ef8bc48cb8f6d3d61cef
    image: docker.io/fixature/oyvindk8sdemo:v1
    imageID: docker.io/fixature/oyvindk8sdemo@sha256:379f0fd17077714e04c0d5a9be2465e82f4fd0a5d8029fe24b90f2b2f65592f4
    lastState: {}
    name: testpod1
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-12-01T10:44:34Z"
  hostIP: 10.224.0.4
  phase: Running
  podIP: 10.244.1.5
  podIPs:
  - ip: 10.244.1.5
  qosClass: BestEffort
  startTime: "2023-12-01T10:44:27Z"
